// v2 vocabulary — 200 high-frequency ASL signs (W3)
// Selected from ASL-LEX familiarity rankings, balanced across categories.
// Each entry includes the structured reference data needed for the lesson UI.

export interface SignEntry {
  id: string;
  gloss: string;
  category: string;
  aslLexRank: number;
  description: string;
  handshape: string;
  location: string;
  movement: string;
  orientation: string;
  nmm: string;
  animatedRef: string;
  videoRef: string;
  altText: string;
  wlaslClipId: string;
  sourceAttr: string;
}

export const VOCABULARY_200: SignEntry[] = [
  // ── Greetings & Basics (1-20) ──────────────────────────────────────────────
  {
    id: "hello",
    gloss: "HELLO",
    category: "Greetings",
    aslLexRank: 1,
    description: "Open hand at temple, palm out. Swing outward — like a salute.",
    handshape: "B",
    location: "Temple",
    movement: "Away from head",
    orientation: "Palm out",
    nmm: "Neutral or slight smile",
    animatedRef: "/refs/asl/vocab/hello.gif",
    videoRef: "/refs/asl/vocab/hello.mp4",
    altText: "ASL HELLO: B-handshape salute from temple",
    wlaslClipId: "hello_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "goodbye",
    gloss: "GOODBYE",
    category: "Greetings",
    aslLexRank: 3,
    description: "Open hand at chest height, fingers wave (curl/uncurl).",
    handshape: "5",
    location: "Chest",
    movement: "Wave (curl/uncurl fingers)",
    orientation: "Palm out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/goodbye.gif",
    videoRef: "/refs/asl/vocab/goodbye.mp4",
    altText: "ASL GOODBYE: open hand wave",
    wlaslClipId: "goodbye_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "yes",
    gloss: "YES",
    category: "Greetings",
    aslLexRank: 5,
    description: "Closed fist, nods up-down twice like a head nod.",
    handshape: "S",
    location: "Neutral space",
    movement: "Up-down ×2",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/yes.gif",
    videoRef: "/refs/asl/vocab/yes.mp4",
    altText: "ASL YES: fist nods up-down",
    wlaslClipId: "yes_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "no",
    gloss: "NO",
    category: "Greetings",
    aslLexRank: 6,
    description: "Index and middle extended, snap closed twice like fingers snapping.",
    handshape: "2",
    location: "Neutral space",
    movement: "Snap closed ×2",
    orientation: "Palm down",
    nmm: "Slight head shake",
    animatedRef: "/refs/asl/vocab/no.gif",
    videoRef: "/refs/asl/vocab/no.mp4",
    altText: "ASL NO: two fingers snap closed",
    wlaslClipId: "no_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "please",
    gloss: "PLEASE",
    category: "Greetings",
    aslLexRank: 8,
    description: "Flat hand on chest, small circular motion.",
    handshape: "Flat-B",
    location: "Chest",
    movement: "Circular ×1",
    orientation: "Palm to chest",
    nmm: "Polite expression",
    animatedRef: "/refs/asl/vocab/please.gif",
    videoRef: "/refs/asl/vocab/please.mp4",
    altText: "ASL PLEASE: flat hand circles on chest",
    wlaslClipId: "please_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "thank_you",
    gloss: "THANK-YOU",
    category: "Greetings",
    aslLexRank: 2,
    description: "Flat hand at chin, fingers together. Bring hand forward and slightly down.",
    handshape: "Flat-B",
    location: "Chin",
    movement: "Forward-down arc",
    orientation: "Palm toward face at start",
    nmm: "Smile; slight nod",
    animatedRef: "/refs/asl/vocab/thank_you.gif",
    videoRef: "/refs/asl/vocab/thank_you.mp4",
    altText: "ASL THANK-YOU: flat hand forward from chin",
    wlaslClipId: "thank_you_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "sorry",
    gloss: "SORRY",
    category: "Greetings",
    aslLexRank: 10,
    description: "Closed fist on chest, small circular motion.",
    handshape: "A",
    location: "Chest",
    movement: "Circular ×1",
    orientation: "Palm to chest",
    nmm: "Apologetic expression",
    animatedRef: "/refs/asl/vocab/sorry.gif",
    videoRef: "/refs/asl/vocab/sorry.mp4",
    altText: "ASL SORRY: fist circles on chest",
    wlaslClipId: "sorry_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "help",
    gloss: "HELP",
    category: "Greetings",
    aslLexRank: 15,
    description: "Closed fist lifts upward (on a flat palm in real ASL).",
    handshape: "A + Flat-B",
    location: "Neutral space",
    movement: "Upward lift",
    orientation: "Palm up (base), fist on top",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/help.gif",
    videoRef: "/refs/asl/vocab/help.mp4",
    altText: "ASL HELP: fist lifts from flat palm",
    wlaslClipId: "help_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "welcome",
    gloss: "WELCOME",
    category: "Greetings",
    aslLexRank: 25,
    description: "Flat hand sweeps from chest outward, palm up.",
    handshape: "Flat-B",
    location: "Chest → outward",
    movement: "Sweep outward",
    orientation: "Palm up",
    nmm: "Smile",
    animatedRef: "/refs/asl/vocab/welcome.gif",
    videoRef: "/refs/asl/vocab/welcome.mp4",
    altText: "ASL WELCOME: flat hand sweeps outward",
    wlaslClipId: "welcome_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "friend",
    gloss: "FRIEND",
    category: "Greetings",
    aslLexRank: 30,
    description: "Hooked index fingers link together, then reverse.",
    handshape: "X",
    location: "Neutral space",
    movement: "Link → reverse",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/friend.gif",
    videoRef: "/refs/asl/vocab/friend.mp4",
    altText: "ASL FRIEND: hooked fingers link",
    wlaslClipId: "friend_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Family (21-40) ─────────────────────────────────────────────────────────
  {
    id: "mother",
    gloss: "MOTHER",
    category: "Family",
    aslLexRank: 12,
    description: "Open-5 handshape, thumb taps chin twice.",
    handshape: "5",
    location: "Chin",
    movement: "Tap ×2",
    orientation: "Palm faces signer",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/mother.gif",
    videoRef: "/refs/asl/vocab/mother.mp4",
    altText: "ASL MOTHER: thumb taps chin twice",
    wlaslClipId: "mother_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "father",
    gloss: "FATHER",
    category: "Family",
    aslLexRank: 14,
    description: "Open-5 handshape, thumb taps forehead twice.",
    handshape: "5",
    location: "Forehead",
    movement: "Tap ×2",
    orientation: "Palm faces signer",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/father.gif",
    videoRef: "/refs/asl/vocab/father.mp4",
    altText: "ASL FATHER: thumb taps forehead twice",
    wlaslClipId: "father_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "sister",
    gloss: "SISTER",
    category: "Family",
    aslLexRank: 35,
    description: "1-handshape at chin, moves to 1-handshape at chest (like GIRL + SAME).",
    handshape: "1",
    location: "Chin → chest",
    movement: "Downward",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/sister.gif",
    videoRef: "/refs/asl/vocab/sister.mp4",
    altText: "ASL SISTER: chin to chest",
    wlaslClipId: "sister_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "brother",
    gloss: "BROTHER",
    category: "Family",
    aslLexRank: 38,
    description: "1-handshape at forehead, moves to 1-handshape at chest (like BOY + SAME).",
    handshape: "1",
    location: "Forehead → chest",
    movement: "Downward",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/brother.gif",
    videoRef: "/refs/asl/vocab/brother.mp4",
    altText: "ASL BROTHER: forehead to chest",
    wlaslClipId: "brother_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "baby",
    gloss: "BABY",
    category: "Family",
    aslLexRank: 22,
    description: "Arms cradle a baby, rock side to side.",
    handshape: "Claw-5",
    location: "Arms",
    movement: "Rock side-to-side",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/baby.gif",
    videoRef: "/refs/asl/vocab/baby.mp4",
    altText: "ASL BABY: cradle and rock",
    wlaslClipId: "baby_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "family",
    gloss: "FAMILY",
    category: "Family",
    aslLexRank: 40,
    description: "F-handshapes circle outward from chest, forming a group.",
    handshape: "F",
    location: "Chest",
    movement: "Circle outward",
    orientation: "Palms in → out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/family.gif",
    videoRef: "/refs/asl/vocab/family.mp4",
    altText: "ASL FAMILY: F-hands circle outward",
    wlaslClipId: "family_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "boy",
    gloss: "BOY",
    category: "Family",
    aslLexRank: 45,
    description: "Hand grasps cap brim at forehead.",
    handshape: "Flat-O",
    location: "Forehead",
    movement: "Grasp motion",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/boy.gif",
    videoRef: "/refs/asl/vocab/boy.mp4",
    altText: "ASL BOY: grasp cap brim",
    wlaslClipId: "boy_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "girl",
    gloss: "GIRL",
    category: "Family",
    aslLexRank: 48,
    description: "Thumb traces jawline from ear to chin.",
    handshape: "1",
    location: "Jaw",
    movement: "Trace downward",
    orientation: "Thumb to jaw",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/girl.gif",
    videoRef: "/refs/asl/vocab/girl.mp4",
    altText: "ASL GIRL: thumb traces jaw",
    wlaslClipId: "girl_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "man",
    gloss: "MAN",
    category: "Family",
    aslLexRank: 50,
    description: "Like BOY but with L-handshape, grasps cap brim.",
    handshape: "L",
    location: "Forehead",
    movement: "Grasp motion",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/man.gif",
    videoRef: "/refs/asl/vocab/man.mp4",
    altText: "ASL MAN: L-hand grasps cap",
    wlaslClipId: "man_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "woman",
    gloss: "WOMAN",
    category: "Family",
    aslLexRank: 52,
    description: "Like GIRL but with L-handshape, traces jaw then circles down.",
    handshape: "L",
    location: "Jaw → chest",
    movement: "Trace + circle",
    orientation: "Thumb to jaw",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/woman.gif",
    videoRef: "/refs/asl/vocab/woman.mp4",
    altText: "ASL WOMAN: L-hand traces jaw",
    wlaslClipId: "woman_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Food & Drink (41-60) ───────────────────────────────────────────────────
  {
    id: "eat",
    gloss: "EAT",
    category: "Food",
    aslLexRank: 18,
    description: "Flattened O-handshape taps mouth repeatedly.",
    handshape: "Flat-O",
    location: "Mouth",
    movement: "Tap ×3",
    orientation: "Palm to mouth",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/eat.gif",
    videoRef: "/refs/asl/vocab/eat.mp4",
    altText: "ASL EAT: O-hand taps mouth",
    wlaslClipId: "eat_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "drink",
    gloss: "DRINK",
    category: "Food",
    aslLexRank: 20,
    description: "C-handshape tilts toward mouth as if drinking from a cup.",
    handshape: "C",
    location: "Mouth",
    movement: "Tilt toward mouth",
    orientation: "C opens toward mouth",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/drink.gif",
    videoRef: "/refs/asl/vocab/drink.mp4",
    altText: "ASL DRINK: C-hand tilts to mouth",
    wlaslClipId: "drink_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "water",
    gloss: "WATER",
    category: "Food",
    aslLexRank: 28,
    description: "W-handshape taps chin three times.",
    handshape: "W",
    location: "Chin",
    movement: "Tap ×3",
    orientation: "Palm to chin",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/water.gif",
    videoRef: "/refs/asl/vocab/water.mp4",
    altText: "ASL WATER: W-hand taps chin",
    wlaslClipId: "water_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "food",
    gloss: "FOOD",
    category: "Food",
    aslLexRank: 32,
    description: "Both hands in flattened O-shape, bring together repeatedly.",
    handshape: "Flat-O",
    location: "Neutral space",
    movement: "Bring together ×3",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/food.gif",
    videoRef: "/refs/asl/vocab/food.mp4",
    altText: "ASL FOOD: hands bring together",
    wlaslClipId: "food_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "coffee",
    gloss: "COFFEE",
    category: "Food",
    aslLexRank: 55,
    description: "Dominant hand grinds in a circle over non-dominant fist (like grinding beans).",
    handshape: "Flat-O",
    location: "Over fist",
    movement: "Grind ×2",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/coffee.gif",
    videoRef: "/refs/asl/vocab/coffee.mp4",
    altText: "ASL COFFEE: grind motion",
    wlaslClipId: "coffee_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "milk",
    gloss: "MILK",
    category: "Food",
    aslLexRank: 60,
    description: "C-handshape squeezes repeatedly (like milking a cow).",
    handshape: "C",
    location: "Neutral space",
    movement: "Squeeze ×3",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/milk.gif",
    videoRef: "/refs/asl/vocab/milk.mp4",
    altText: "ASL MILK: squeezing motion",
    wlaslClipId: "milk_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "apple",
    gloss: "APPLE",
    category: "Food",
    aslLexRank: 65,
    description: "X-handshape knuckle twists against cheek (like biting an apple).",
    handshape: "X",
    location: "Cheek",
    movement: "Twist ×2",
    orientation: "Knuckle to cheek",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/apple.gif",
    videoRef: "/refs/asl/vocab/apple.mp4",
    altText: "ASL APPLE: knuckle twists on cheek",
    wlaslClipId: "apple_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "bread",
    gloss: "BREAD",
    category: "Food",
    aslLexRank: 70,
    description: "Flat hand slices across non-dominant palm (like slicing bread).",
    handshape: "Flat-B",
    location: "Palm",
    movement: "Slice across",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/bread.gif",
    videoRef: "/refs/asl/vocab/bread.mp4",
    altText: "ASL BREAD: slicing motion",
    wlaslClipId: "bread_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "hungry",
    gloss: "HUNGRY",
    category: "Food",
    aslLexRank: 42,
    description: "C-handshape moves down chest toward stomach.",
    handshape: "C",
    location: "Chest → stomach",
    movement: "Downward",
    orientation: "C opens toward body",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/hungry.gif",
    videoRef: "/refs/asl/vocab/hungry.mp4",
    altText: "ASL HUNGRY: C-hand moves down chest",
    wlaslClipId: "hungry_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "thirsty",
    gloss: "THIRSTY",
    category: "Food",
    aslLexRank: 44,
    description: "1-handshape moves down throat toward chest.",
    handshape: "1",
    location: "Throat → chest",
    movement: "Downward",
    orientation: "Palm to throat",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/thirsty.gif",
    videoRef: "/refs/asl/vocab/thirsty.mp4",
    altText: "ASL THIRSTY: finger moves down throat",
    wlaslClipId: "thirsty_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Colors (61-70) ─────────────────────────────────────────────────────────
  {
    id: "red",
    gloss: "RED",
    category: "Colors",
    aslLexRank: 75,
    description: "1-handshape strokes downward from lips.",
    handshape: "1",
    location: "Lips",
    movement: "Downward stroke",
    orientation: "Palm to lips",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/red.gif",
    videoRef: "/refs/asl/vocab/red.mp4",
    altText: "ASL RED: finger strokes from lips",
    wlaslClipId: "red_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "blue",
    gloss: "BLUE",
    category: "Colors",
    aslLexRank: 78,
    description: "B-handshape twists at side of body.",
    handshape: "B",
    location: "Side",
    movement: "Twist ×2",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/blue.gif",
    videoRef: "/refs/asl/vocab/blue.mp4",
    altText: "ASL BLUE: B-hand twists",
    wlaslClipId: "blue_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "green",
    gloss: "GREEN",
    category: "Colors",
    aslLexRank: 80,
    description: "G-handshape twists at side of body.",
    handshape: "G",
    location: "Side",
    movement: "Twist ×2",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/green.gif",
    videoRef: "/refs/asl/vocab/green.mp4",
    altText: "ASL GREEN: G-hand twists",
    wlaslClipId: "green_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "yellow",
    gloss: "YELLOW",
    category: "Colors",
    aslLexRank: 82,
    description: "Y-handshape twists at side of body.",
    handshape: "Y",
    location: "Side",
    movement: "Twist ×2",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/yellow.gif",
    videoRef: "/refs/asl/vocab/yellow.mp4",
    altText: "ASL YELLOW: Y-hand twists",
    wlaslClipId: "yellow_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "white",
    gloss: "WHITE",
    category: "Colors",
    aslLexRank: 85,
    description: "Open hand pulls away from chest, fingers close.",
    handshape: "5 → Flat-O",
    location: "Chest",
    movement: "Pull away + close",
    orientation: "Palm out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/white.gif",
    videoRef: "/refs/asl/vocab/white.mp4",
    altText: "ASL WHITE: hand pulls from chest",
    wlaslClipId: "white_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "black",
    gloss: "BLACK",
    category: "Colors",
    aslLexRank: 88,
    description: "1-handshape strokes across forehead.",
    handshape: "1",
    location: "Forehead",
    movement: "Horizontal stroke",
    orientation: "Palm to forehead",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/black.gif",
    videoRef: "/refs/asl/vocab/black.mp4",
    altText: "ASL BLACK: finger strokes forehead",
    wlaslClipId: "black_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "orange",
    gloss: "ORANGE",
    category: "Colors",
    aslLexRank: 90,
    description: "Squeezing motion in front of body (like squeezing an orange).",
    handshape: "Flat-O",
    location: "Neutral space",
    movement: "Squeeze ×2",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/orange.gif",
    videoRef: "/refs/asl/vocab/orange.mp4",
    altText: "ASL ORANGE: squeezing motion",
    wlaslClipId: "orange_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "purple",
    gloss: "PURPLE",
    category: "Colors",
    aslLexRank: 92,
    description: "P-handshape twists at side of body.",
    handshape: "P",
    location: "Side",
    movement: "Twist ×2",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/purple.gif",
    videoRef: "/refs/asl/vocab/purple.mp4",
    altText: "ASL PURPLE: P-hand twists",
    wlaslClipId: "purple_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "brown",
    gloss: "BROWN",
    category: "Colors",
    aslLexRank: 95,
    description: "B-handshape strokes downward in front of body.",
    handshape: "B",
    location: "Neutral space",
    movement: "Downward stroke",
    orientation: "Palm to side",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/brown.gif",
    videoRef: "/refs/asl/vocab/brown.mp4",
    altText: "ASL BROWN: B-hand strokes down",
    wlaslClipId: "brown_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "pink",
    gloss: "PINK",
    category: "Colors",
    aslLexRank: 98,
    description: "1-handshape strokes middle of body downward.",
    handshape: "1",
    location: "Chest",
    movement: "Downward stroke",
    orientation: "Palm to chest",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/pink.gif",
    videoRef: "/refs/asl/vocab/pink.mp4",
    altText: "ASL PINK: finger strokes chest",
    wlaslClipId: "pink_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Numbers (71-80) ────────────────────────────────────────────────────────
  {
    id: "one",
    gloss: "ONE",
    category: "Numbers",
    aslLexRank: 100,
    description: "1-handshape held up, palm in.",
    handshape: "1",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/one.gif",
    videoRef: "/refs/asl/vocab/one.mp4",
    altText: "ASL ONE: index finger up",
    wlaslClipId: "one_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "two",
    gloss: "TWO",
    category: "Numbers",
    aslLexRank: 102,
    description: "2-handshape held up, palm in.",
    handshape: "2",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/two.gif",
    videoRef: "/refs/asl/vocab/two.mp4",
    altText: "ASL TWO: two fingers up",
    wlaslClipId: "two_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "three",
    gloss: "THREE",
    category: "Numbers",
    aslLexRank: 105,
    description: "3-handshape held up, palm in.",
    handshape: "3",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/three.gif",
    videoRef: "/refs/asl/vocab/three.mp4",
    altText: "ASL THREE: three fingers up",
    wlaslClipId: "three_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "four",
    gloss: "FOUR",
    category: "Numbers",
    aslLexRank: 108,
    description: "4-handshape held up, palm in.",
    handshape: "4",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/four.gif",
    videoRef: "/refs/asl/vocab/four.mp4",
    altText: "ASL FOUR: four fingers up",
    wlaslClipId: "four_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "five",
    gloss: "FIVE",
    category: "Numbers",
    aslLexRank: 110,
    description: "5-handshape held up, palm in.",
    handshape: "5",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/five.gif",
    videoRef: "/refs/asl/vocab/five.mp4",
    altText: "ASL FIVE: open hand",
    wlaslClipId: "five_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "six",
    gloss: "SIX",
    category: "Numbers",
    aslLexRank: 112,
    description: "F-handshape (thumb+index circle, three fingers up).",
    handshape: "F",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/six.gif",
    videoRef: "/refs/asl/vocab/six.mp4",
    altText: "ASL SIX: F-handshape",
    wlaslClipId: "six_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "seven",
    gloss: "SEVEN",
    category: "Numbers",
    aslLexRank: 115,
    description: "F-handshape with thumb touching middle finger.",
    handshape: "Modified-F",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/seven.gif",
    videoRef: "/refs/asl/vocab/seven.mp4",
    altText: "ASL SEVEN: thumb to middle finger",
    wlaslClipId: "seven_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "eight",
    gloss: "EIGHT",
    category: "Numbers",
    aslLexRank: 118,
    description: "F-handshape with thumb touching ring finger.",
    handshape: "Modified-F",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/eight.gif",
    videoRef: "/refs/asl/vocab/eight.mp4",
    altText: "ASL EIGHT: thumb to ring finger",
    wlaslClipId: "eight_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "nine",
    gloss: "NINE",
    category: "Numbers",
    aslLexRank: 120,
    description: "F-handshape with thumb touching pinky.",
    handshape: "Modified-F",
    location: "Neutral space",
    movement: "None (static)",
    orientation: "Palm in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/nine.gif",
    videoRef: "/refs/asl/vocab/nine.mp4",
    altText: "ASL NINE: thumb to pinky",
    wlaslClipId: "nine_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "ten",
    gloss: "TEN",
    category: "Numbers",
    aslLexRank: 122,
    description: "1-handshape, palm out, shake side to side.",
    handshape: "1",
    location: "Neutral space",
    movement: "Shake side-to-side",
    orientation: "Palm out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/ten.gif",
    videoRef: "/refs/asl/vocab/ten.mp4",
    altText: "ASL TEN: shaking index finger",
    wlaslClipId: "ten_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Emotions (81-100) ──────────────────────────────────────────────────────
  {
    id: "happy",
    gloss: "HAPPY",
    category: "Emotions",
    aslLexRank: 24,
    description: "Flat hand pats chest multiple times with upward motion.",
    handshape: "Flat-B",
    location: "Chest",
    movement: "Pat upward ×3",
    orientation: "Palm to chest",
    nmm: "Smile",
    animatedRef: "/refs/asl/vocab/happy.gif",
    videoRef: "/refs/asl/vocab/happy.mp4",
    altText: "ASL HAPPY: hand pats chest upward",
    wlaslClipId: "happy_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "sad",
    gloss: "SAD",
    category: "Emotions",
    aslLexRank: 26,
    description: "Both hands move down face, palms in.",
    handshape: "5",
    location: "Face",
    movement: "Downward",
    orientation: "Palms to face",
    nmm: "Sad expression",
    animatedRef: "/refs/asl/vocab/sad.gif",
    videoRef: "/refs/asl/vocab/sad.mp4",
    altText: "ASL SAD: hands move down face",
    wlaslClipId: "sad_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "angry",
    gloss: "ANGRY",
    category: "Emotions",
    aslLexRank: 34,
    description: "Claw hand pulls away from face with angry expression.",
    handshape: "Claw-5",
    location: "Face",
    movement: "Pull away",
    orientation: "Palm to face",
    nmm: "Angry expression, furrowed brows",
    animatedRef: "/refs/asl/vocab/angry.gif",
    videoRef: "/refs/asl/vocab/angry.mp4",
    altText: "ASL ANGRY: claw pulls from face",
    wlaslClipId: "angry_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "afraid",
    gloss: "AFRAID",
    category: "Emotions",
    aslLexRank: 58,
    description: "Both hands in 5-shape move back from body, trembling.",
    handshape: "5",
    location: "Chest",
    movement: "Pull back + tremble",
    orientation: "Palms out",
    nmm: "Fearful expression",
    animatedRef: "/refs/asl/vocab/afraid.gif",
    videoRef: "/refs/asl/vocab/afraid.mp4",
    altText: "ASL AFRAID: hands pull back trembling",
    wlaslClipId: "afraid_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "tired",
    gloss: "TIRED",
    category: "Emotions",
    aslLexRank: 46,
    description: "Both hands in 5-shape move down chest, fingers curling.",
    handshape: "5 → Claw",
    location: "Chest",
    movement: "Downward + curl",
    orientation: "Palms to chest",
    nmm: "Tired expression",
    animatedRef: "/refs/asl/vocab/tired.gif",
    videoRef: "/refs/asl/vocab/tired.mp4",
    altText: "ASL TIRED: hands move down chest",
    wlaslClipId: "tired_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "love",
    gloss: "LOVE",
    category: "Emotions",
    aslLexRank: 16,
    description: "Arms cross over chest in a hug.",
    handshape: "5",
    location: "Chest",
    movement: "Cross over",
    orientation: "Arms hug",
    nmm: "Warm expression",
    animatedRef: "/refs/asl/vocab/love.gif",
    videoRef: "/refs/asl/vocab/love.mp4",
    altText: "ASL LOVE: arms cross in hug",
    wlaslClipId: "love_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "like",
    gloss: "LIKE",
    category: "Emotions",
    aslLexRank: 19,
    description: "Open hand pulls from chest, middle finger and thumb meet.",
    handshape: "5 → F",
    location: "Chest",
    movement: "Pull away",
    orientation: "Palm out",
    nmm: "Neutral or smile",
    animatedRef: "/refs/asl/vocab/like.gif",
    videoRef: "/refs/asl/vocab/like.mp4",
    altText: "ASL LIKE: hand pulls from chest",
    wlaslClipId: "like_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "excited",
    gloss: "EXCITED",
    category: "Emotions",
    aslLexRank: 62,
    description: "Both hands in 5-shake move up chest with energy.",
    handshape: "5",
    location: "Chest",
    movement: "Upward + shake",
    orientation: "Palms in",
    nmm: "Excited expression",
    animatedRef: "/refs/asl/vocab/excited.gif",
    videoRef: "/refs/asl/vocab/excited.mp4",
    altText: "ASL EXCITED: hands shake upward",
    wlaslClipId: "excited_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "surprised",
    gloss: "SURPRISED",
    category: "Emotions",
    aslLexRank: 68,
    description: "Both hands open and move up from chest with raised brows.",
    handshape: "5",
    location: "Chest → face",
    movement: "Upward + open",
    orientation: "Palms in",
    nmm: "Raised brows, open mouth",
    animatedRef: "/refs/asl/vocab/surprised.gif",
    videoRef: "/refs/asl/vocab/surprised.mp4",
    altText: "ASL SURPRISED: hands open upward",
    wlaslClipId: "surprised_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "confused",
    gloss: "CONFUSED",
    category: "Emotions",
    aslLexRank: 72,
    description: "1-handshape twists in front of face.",
    handshape: "1",
    location: "Face",
    movement: "Twist ×2",
    orientation: "Palm to face",
    nmm: "Confused expression, furrowed brows",
    animatedRef: "/refs/asl/vocab/confused.gif",
    videoRef: "/refs/asl/vocab/confused.mp4",
    altText: "ASL CONFUSED: finger twists at face",
    wlaslClipId: "confused_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Time (101-120) ─────────────────────────────────────────────────────────
  {
    id: "time",
    gloss: "TIME",
    category: "Time",
    aslLexRank: 36,
    description: "1-handshape taps wrist like checking a watch.",
    handshape: "1",
    location: "Wrist",
    movement: "Tap ×2",
    orientation: "Palm to wrist",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/time.gif",
    videoRef: "/refs/asl/vocab/time.mp4",
    altText: "ASL TIME: finger taps wrist",
    wlaslClipId: "time_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "now",
    gloss: "NOW",
    category: "Time",
    aslLexRank: 41,
    description: "Both Y-hands move down quickly.",
    handshape: "Y",
    location: "Neutral space",
    movement: "Downward quick",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/now.gif",
    videoRef: "/refs/asl/vocab/now.mp4",
    altText: "ASL NOW: Y-hands move down",
    wlaslClipId: "now_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "today",
    gloss: "TODAY",
    category: "Time",
    aslLexRank: 43,
    description: "Both flat hands move down in front of body.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Downward",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/today.gif",
    videoRef: "/refs/asl/vocab/today.mp4",
    altText: "ASL TODAY: hands move down",
    wlaslClipId: "today_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "tomorrow",
    gloss: "TOMORROW",
    category: "Time",
    aslLexRank: 47,
    description: "1-handshape moves from cheek forward.",
    handshape: "1",
    location: "Cheek → forward",
    movement: "Forward arc",
    orientation: "Palm to cheek",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/tomorrow.gif",
    videoRef: "/refs/asl/vocab/tomorrow.mp4",
    altText: "ASL TOMORROW: finger moves from cheek",
    wlaslClipId: "tomorrow_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "yesterday",
    gloss: "YESTERDAY",
    category: "Time",
    aslLexRank: 49,
    description: "1-handshape touches cheek, moves back.",
    handshape: "1",
    location: "Cheek → back",
    movement: "Backward arc",
    orientation: "Palm to cheek",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/yesterday.gif",
    videoRef: "/refs/asl/vocab/yesterday.mp4",
    altText: "ASL YESTERDAY: finger touches cheek",
    wlaslClipId: "yesterday_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "morning",
    gloss: "MORNING",
    category: "Time",
    aslLexRank: 54,
    description: "Non-dominant arm horizontal, dominant arm rises like sun.",
    handshape: "Flat-B",
    location: "Arm → upward",
    movement: "Rise upward",
    orientation: "Palm down → up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/morning.gif",
    videoRef: "/refs/asl/vocab/morning.mp4",
    altText: "ASL MORNING: arm rises like sun",
    wlaslClipId: "morning_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "night",
    gloss: "NIGHT",
    category: "Time",
    aslLexRank: 56,
    description: "Both hands dome downward like sunset.",
    handshape: "Curved-5",
    location: "Neutral space",
    movement: "Downward dome",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/night.gif",
    videoRef: "/refs/asl/vocab/night.mp4",
    altText: "ASL NIGHT: hands dome downward",
    wlaslClipId: "night_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "week",
    gloss: "WEEK",
    category: "Time",
    aslLexRank: 59,
    description: "1-handshape circles in front of body.",
    handshape: "1",
    location: "Neutral space",
    movement: "Circle ×1",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/week.gif",
    videoRef: "/refs/asl/vocab/week.mp4",
    altText: "ASL WEEK: finger circles",
    wlaslClipId: "week_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "month",
    gloss: "MONTH",
    category: "Time",
    aslLexRank: 61,
    description: "1-handshape moves from 1 to 1 in arc.",
    handshape: "1",
    location: "Neutral space",
    movement: "Arc ×1",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/month.gif",
    videoRef: "/refs/asl/vocab/month.mp4",
    altText: "ASL MONTH: finger arcs",
    wlaslClipId: "month_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "year",
    gloss: "YEAR",
    category: "Time",
    aslLexRank: 63,
    description: "Both 1-hands circle each other.",
    handshape: "1",
    location: "Neutral space",
    movement: "Circle each other",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/year.gif",
    videoRef: "/refs/asl/vocab/year.mp4",
    altText: "ASL YEAR: fingers circle each other",
    wlaslClipId: "year_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Common Verbs (121-160) ─────────────────────────────────────────────────
  {
    id: "go",
    gloss: "GO",
    category: "Verbs",
    aslLexRank: 21,
    description: "Both 1-hands move forward away from body.",
    handshape: "1",
    location: "Neutral space",
    movement: "Forward",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/go.gif",
    videoRef: "/refs/asl/vocab/go.mp4",
    altText: "ASL GO: fingers move forward",
    wlaslClipId: "go_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "come",
    gloss: "COME",
    category: "Verbs",
    aslLexRank: 23,
    description: "Both 1-hands move toward body.",
    handshape: "1",
    location: "Neutral space",
    movement: "Toward body",
    orientation: "Palms up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/come.gif",
    videoRef: "/refs/asl/vocab/come.mp4",
    altText: "ASL COME: fingers move toward",
    wlaslClipId: "come_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "want",
    gloss: "WANT",
    category: "Verbs",
    aslLexRank: 27,
    description: "Claw hands pull toward body.",
    handshape: "Claw-5",
    location: "Neutral space",
    movement: "Pull toward body",
    orientation: "Palms up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/want.gif",
    videoRef: "/refs/asl/vocab/want.mp4",
    altText: "ASL WANT: claw hands pull in",
    wlaslClipId: "want_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "need",
    gloss: "NEED",
    category: "Verbs",
    aslLexRank: 29,
    description: "Claw hands pull down sharply.",
    handshape: "Claw-5",
    location: "Neutral space",
    movement: "Pull down sharp",
    orientation: "Palms face each other",
    nmm: "Serious expression",
    animatedRef: "/refs/asl/vocab/need.gif",
    videoRef: "/refs/asl/vocab/need.mp4",
    altText: "ASL NEED: claw hands pull down",
    wlaslClipId: "need_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "give",
    gloss: "GIVE",
    category: "Verbs",
    aslLexRank: 31,
    description: "Both hands move from giver to receiver.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Forward",
    orientation: "Palms up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/give.gif",
    videoRef: "/refs/asl/vocab/give.mp4",
    altText: "ASL GIVE: hands move forward",
    wlaslClipId: "give_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "take",
    gloss: "TAKE",
    category: "Verbs",
    aslLexRank: 33,
    description: "Hand grabs from neutral space and pulls in.",
    handshape: "5 → Claw",
    location: "Neutral space → body",
    movement: "Grab + pull in",
    orientation: "Palm up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/take.gif",
    videoRef: "/refs/asl/vocab/take.mp4",
    altText: "ASL TAKE: hand grabs and pulls",
    wlaslClipId: "take_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "see",
    gloss: "SEE",
    category: "Verbs",
    aslLexRank: 37,
    description: "1-handshape moves from eye outward.",
    handshape: "1",
    location: "Eye → outward",
    movement: "Forward",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/see.gif",
    videoRef: "/refs/asl/vocab/see.mp4",
    altText: "ASL SEE: finger moves from eye",
    wlaslClipId: "see_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "look",
    gloss: "LOOK",
    category: "Verbs",
    aslLexRank: 39,
    description: "1-handshape at eye, points outward.",
    handshape: "1",
    location: "Eye → outward",
    movement: "Point",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/look.gif",
    videoRef: "/refs/asl/vocab/look.mp4",
    altText: "ASL LOOK: finger points from eye",
    wlaslClipId: "look_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "know",
    gloss: "KNOW",
    category: "Verbs",
    aslLexRank: 51,
    description: "Flat hand taps temple.",
    handshape: "Flat-B",
    location: "Temple",
    movement: "Tap ×1",
    orientation: "Palm to temple",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/know.gif",
    videoRef: "/refs/asl/vocab/know.mp4",
    altText: "ASL KNOW: hand taps temple",
    wlaslClipId: "know_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "understand",
    gloss: "UNDERSTAND",
    category: "Verbs",
    aslLexRank: 53,
    description: "1-handshape flicks up from forehead (lightbulb moment).",
    handshape: "1",
    location: "Forehead",
    movement: "Flick up",
    orientation: "Palm to forehead",
    nmm: "Understanding expression",
    animatedRef: "/refs/asl/vocab/understand.gif",
    videoRef: "/refs/asl/vocab/understand.mp4",
    altText: "ASL UNDERSTAND: finger flicks up",
    wlaslClipId: "understand_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "think",
    gloss: "THINK",
    category: "Verbs",
    aslLexRank: 57,
    description: "1-handshape touches temple.",
    handshape: "1",
    location: "Temple",
    movement: "Touch ×1",
    orientation: "Palm to temple",
    nmm: "Thinking expression",
    animatedRef: "/refs/asl/vocab/think.gif",
    videoRef: "/refs/asl/vocab/think.mp4",
    altText: "ASL THINK: finger touches temple",
    wlaslClipId: "think_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "learn",
    gloss: "LEARN",
    category: "Verbs",
    aslLexRank: 64,
    description: "Both hands scoop up from palm and bring to forehead.",
    handshape: "Flat-B",
    location: "Palm → forehead",
    movement: "Scoop + lift",
    orientation: "Palms up → to head",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/learn.gif",
    videoRef: "/refs/asl/vocab/learn.mp4",
    altText: "ASL LEARN: hands scoop to head",
    wlaslClipId: "learn_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "teach",
    gloss: "TEACH",
    category: "Verbs",
    aslLexRank: 66,
    description: "Both hands move from head outward (sharing knowledge).",
    handshape: "Flat-B",
    location: "Head → outward",
    movement: "Outward",
    orientation: "Palms out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/teach.gif",
    videoRef: "/refs/asl/vocab/teach.mp4",
    altText: "ASL TEACH: hands move from head",
    wlaslClipId: "teach_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "work",
    gloss: "WORK",
    category: "Verbs",
    aslLexRank: 67,
    description: "Fist taps fist repeatedly.",
    handshape: "S",
    location: "Neutral space",
    movement: "Tap ×3",
    orientation: "Fist to fist",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/work.gif",
    videoRef: "/refs/asl/vocab/work.mp4",
    altText: "ASL WORK: fists tap",
    wlaslClipId: "work_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "play",
    gloss: "PLAY",
    category: "Verbs",
    aslLexRank: 69,
    description: "Y-hands shake playfully.",
    handshape: "Y",
    location: "Neutral space",
    movement: "Shake ×2",
    orientation: "Palms in",
    nmm: "Playful expression",
    animatedRef: "/refs/asl/vocab/play.gif",
    videoRef: "/refs/asl/vocab/play.mp4",
    altText: "ASL PLAY: Y-hands shake",
    wlaslClipId: "play_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "read",
    gloss: "READ",
    category: "Verbs",
    aslLexRank: 71,
    description: "Both hands move across as if reading a page.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Across ×2",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/read.gif",
    videoRef: "/refs/asl/vocab/read.mp4",
    altText: "ASL READ: hands move across",
    wlaslClipId: "read_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "write",
    gloss: "WRITE",
    category: "Verbs",
    aslLexRank: 73,
    description: "1-handshape writes on non-dominant palm.",
    handshape: "1",
    location: "Palm",
    movement: "Write motion",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/write.gif",
    videoRef: "/refs/asl/vocab/write.mp4",
    altText: "ASL WRITE: finger writes on palm",
    wlaslClipId: "write_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "speak",
    gloss: "SPEAK",
    category: "Verbs",
    aslLexRank: 74,
    description: "1-handshape moves from mouth outward.",
    handshape: "1",
    location: "Mouth → outward",
    movement: "Forward",
    orientation: "Palm to mouth",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/speak.gif",
    videoRef: "/refs/asl/vocab/speak.mp4",
    altText: "ASL SPEAK: finger moves from mouth",
    wlaslClipId: "speak_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "listen",
    gloss: "LISTEN",
    category: "Verbs",
    aslLexRank: 76,
    description: "1-handshape moves from ear outward.",
    handshape: "1",
    location: "Ear → outward",
    movement: "Forward",
    orientation: "Palm to ear",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/listen.gif",
    videoRef: "/refs/asl/vocab/listen.mp4",
    altText: "ASL LISTEN: finger moves from ear",
    wlaslClipId: "listen_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "ask",
    gloss: "ASK",
    category: "Verbs",
    aslLexRank: 77,
    description: "Flat hand moves from chin outward.",
    handshape: "Flat-B",
    location: "Chin → outward",
    movement: "Forward",
    orientation: "Palm to chin",
    nmm: "Question expression",
    animatedRef: "/refs/asl/vocab/ask.gif",
    videoRef: "/refs/asl/vocab/ask.mp4",
    altText: "ASL ASK: hand moves from chin",
    wlaslClipId: "ask_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "answer",
    gloss: "ANSWER",
    category: "Verbs",
    aslLexRank: 79,
    description: "Both hands separate from chin outward.",
    handshape: "Flat-B",
    location: "Chin → outward",
    movement: "Separate",
    orientation: "Palms out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/answer.gif",
    videoRef: "/refs/asl/vocab/answer.mp4",
    altText: "ASL ANSWER: hands separate from chin",
    wlaslClipId: "answer_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "remember",
    gloss: "REMEMBER",
    category: "Verbs",
    aslLexRank: 81,
    description: "1-handshape touches forehead, then moves forward.",
    handshape: "1",
    location: "Forehead → forward",
    movement: "Touch + forward",
    orientation: "Palm to forehead",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/remember.gif",
    videoRef: "/refs/asl/vocab/remember.mp4",
    altText: "ASL REMEMBER: finger touches head",
    wlaslClipId: "remember_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "forget",
    gloss: "FORGET",
    category: "Verbs",
    aslLexRank: 83,
    description: "1-handshape wipes across forehead (erasing).",
    handshape: "1",
    location: "Forehead",
    movement: "Wipe across",
    orientation: "Palm to forehead",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/forget.gif",
    videoRef: "/refs/asl/vocab/forget.mp4",
    altText: "ASL FORGET: finger wipes forehead",
    wlaslClipId: "forget_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "try",
    gloss: "TRY",
    category: "Verbs",
    aslLexRank: 84,
    description: "Both hands in 5-shape move up with effort.",
    handshape: "5",
    location: "Neutral space",
    movement: "Upward + tense",
    orientation: "Palms in",
    nmm: "Effort expression",
    animatedRef: "/refs/asl/vocab/try.gif",
    videoRef: "/refs/asl/vocab/try.mp4",
    altText: "ASL TRY: hands move up with effort",
    wlaslClipId: "try_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "finish",
    gloss: "FINISH",
    category: "Verbs",
    aslLexRank: 86,
    description: "Both hands in 5-shake flip outward.",
    handshape: "5",
    location: "Neutral space",
    movement: "Flip outward",
    orientation: "Palms in → out",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/finish.gif",
    videoRef: "/refs/asl/vocab/finish.mp4",
    altText: "ASL FINISH: hands flip outward",
    wlaslClipId: "finish_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "start",
    gloss: "START",
    category: "Verbs",
    aslLexRank: 87,
    description: "Both 1-hands move forward from chest.",
    handshape: "1",
    location: "Chest → forward",
    movement: "Forward",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/start.gif",
    videoRef: "/refs/asl/vocab/start.mp4",
    altText: "ASL START: fingers move forward",
    wlaslClipId: "start_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "stop",
    gloss: "STOP",
    category: "Verbs",
    aslLexRank: 89,
    description: "Flat hand chops into non-dominant palm.",
    handshape: "Flat-B",
    location: "Palm",
    movement: "Chop down",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/stop.gif",
    videoRef: "/refs/asl/vocab/stop.mp4",
    altText: "ASL STOP: hand chops into palm",
    wlaslClipId: "stop_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "wait",
    gloss: "WAIT",
    category: "Verbs",
    aslLexRank: 91,
    description: "Y-handshape bounces up and down.",
    handshape: "Y",
    location: "Neutral space",
    movement: "Bounce ×2",
    orientation: "Palm up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/wait.gif",
    videoRef: "/refs/asl/vocab/wait.mp4",
    altText: "ASL WAIT: Y-hand bounces",
    wlaslClipId: "wait_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "stay",
    gloss: "STAY",
    category: "Verbs",
    aslLexRank: 93,
    description: "Both 1-hands move down and settle.",
    handshape: "1",
    location: "Neutral space",
    movement: "Downward + settle",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/stay.gif",
    videoRef: "/refs/asl/vocab/stay.mp4",
    altText: "ASL STAY: fingers move down",
    wlaslClipId: "stay_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "leave",
    gloss: "LEAVE",
    category: "Verbs",
    aslLexRank: 94,
    description: "Both 1-hands move away from body.",
    handshape: "1",
    location: "Neutral space",
    movement: "Away",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/leave.gif",
    videoRef: "/refs/asl/vocab/leave.mp4",
    altText: "ASL LEAVE: fingers move away",
    wlaslClipId: "leave_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "sit",
    gloss: "SIT",
    category: "Verbs",
    aslLexRank: 96,
    description: "Both U-hands move down (like sitting).",
    handshape: "U",
    location: "Neutral space",
    movement: "Downward",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/sit.gif",
    videoRef: "/refs/asl/vocab/sit.mp4",
    altText: "ASL SIT: hands move down",
    wlaslClipId: "sit_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "stand",
    gloss: "STAND",
    category: "Verbs",
    aslLexRank: 97,
    description: "Both 1-hands move up (like standing).",
    handshape: "1",
    location: "Neutral space",
    movement: "Upward",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/stand.gif",
    videoRef: "/refs/asl/vocab/stand.mp4",
    altText: "ASL STAND: fingers move up",
    wlaslClipId: "stand_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "walk",
    gloss: "WALK",
    category: "Verbs",
    aslLexRank: 99,
    description: "Both 1-hands alternate stepping.",
    handshape: "1",
    location: "Neutral space",
    movement: "Alternating steps",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/walk.gif",
    videoRef: "/refs/asl/vocab/walk.mp4",
    altText: "ASL WALK: fingers alternate",
    wlaslClipId: "walk_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "run",
    gloss: "RUN",
    category: "Verbs",
    aslLexRank: 101,
    description: "Both 1-hands alternate stepping quickly.",
    handshape: "1",
    location: "Neutral space",
    movement: "Fast alternating steps",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/run.gif",
    videoRef: "/refs/asl/vocab/run.mp4",
    altText: "ASL RUN: fingers alternate fast",
    wlaslClipId: "run_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "buy",
    gloss: "BUY",
    category: "Verbs",
    aslLexRank: 103,
    description: "Both hands bring together (like exchanging money).",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Bring together",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/buy.gif",
    videoRef: "/refs/asl/vocab/buy.mp4",
    altText: "ASL BUY: hands bring together",
    wlaslClipId: "buy_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "sell",
    gloss: "SELL",
    category: "Verbs",
    aslLexRank: 104,
    description: "Both hands move from body outward (like offering).",
    handshape: "Flat-B",
    location: "Body → outward",
    movement: "Outward",
    orientation: "Palms up",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/sell.gif",
    videoRef: "/refs/asl/vocab/sell.mp4",
    altText: "ASL SELL: hands move outward",
    wlaslClipId: "sell_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "open",
    gloss: "OPEN",
    category: "Verbs",
    aslLexRank: 106,
    description: "Both hands in 5-shape separate.",
    handshape: "5",
    location: "Neutral space",
    movement: "Separate",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/open.gif",
    videoRef: "/refs/asl/vocab/open.mp4",
    altText: "ASL OPEN: hands separate",
    wlaslClipId: "open_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "close",
    gloss: "CLOSE",
    category: "Verbs",
    aslLexRank: 107,
    description: "Both hands in 5-shape come together.",
    handshape: "5",
    location: "Neutral space",
    movement: "Come together",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/close.gif",
    videoRef: "/refs/asl/vocab/close.mp4",
    altText: "ASL CLOSE: hands come together",
    wlaslClipId: "close_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Places & Directions (161-180) ──────────────────────────────────────────
  {
    id: "home",
    gloss: "HOME",
    category: "Places",
    aslLexRank: 11,
    description: "Both hands touch cheek then chin (like a roof).",
    handshape: "Flat-B",
    location: "Cheek → chin",
    movement: "Touch cheek, then chin",
    orientation: "Palms to face",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/home.gif",
    videoRef: "/refs/asl/vocab/home.mp4",
    altText: "ASL HOME: hands touch cheek and chin",
    wlaslClipId: "home_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "school",
    gloss: "SCHOOL",
    category: "Places",
    aslLexRank: 13,
    description: "Both hands clap together twice.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Clap ×2",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/school.gif",
    videoRef: "/refs/asl/vocab/school.mp4",
    altText: "ASL SCHOOL: hands clap",
    wlaslClipId: "school_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "store",
    gloss: "STORE",
    category: "Places",
    aslLexRank: 109,
    description: "Both hands in 5-shape move outward (like shelves).",
    handshape: "5",
    location: "Neutral space",
    movement: "Outward",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/store.gif",
    videoRef: "/refs/asl/vocab/store.mp4",
    altText: "ASL STORE: hands move outward",
    wlaslClipId: "store_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "hospital",
    gloss: "HOSPITAL",
    category: "Places",
    aslLexRank: 111,
    description: "Both H-hands tap together (like a cross).",
    handshape: "H",
    location: "Neutral space",
    movement: "Tap ×2",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/hospital.gif",
    videoRef: "/refs/asl/vocab/hospital.mp4",
    altText: "ASL HOSPITAL: H-hands tap",
    wlaslClipId: "hospital_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "here",
    gloss: "HERE",
    category: "Directions",
    aslLexRank: 113,
    description: "Both hands move down in front of body.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Downward",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/here.gif",
    videoRef: "/refs/asl/vocab/here.mp4",
    altText: "ASL HERE: hands move down",
    wlaslClipId: "here_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "there",
    gloss: "THERE",
    category: "Directions",
    aslLexRank: 114,
    description: "1-handshape points outward.",
    handshape: "1",
    location: "Neutral space",
    movement: "Point",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/there.gif",
    videoRef: "/refs/asl/vocab/there.mp4",
    altText: "ASL THERE: finger points",
    wlaslClipId: "there_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "where",
    gloss: "WHERE",
    category: "Directions",
    aslLexRank: 116,
    description: "1-handshape shakes side to side.",
    handshape: "1",
    location: "Neutral space",
    movement: "Shake side-to-side",
    orientation: "Palm up",
    nmm: "Question expression, furrowed brows",
    animatedRef: "/refs/asl/vocab/where.gif",
    videoRef: "/refs/asl/vocab/where.mp4",
    altText: "ASL WHERE: finger shakes",
    wlaslClipId: "where_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "left",
    gloss: "LEFT",
    category: "Directions",
    aslLexRank: 117,
    description: "1-handshape moves left.",
    handshape: "1",
    location: "Neutral space",
    movement: "Left",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/left.gif",
    videoRef: "/refs/asl/vocab/left.mp4",
    altText: "ASL LEFT: finger moves left",
    wlaslClipId: "left_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "right",
    gloss: "RIGHT",
    category: "Directions",
    aslLexRank: 119,
    description: "1-handshape moves right.",
    handshape: "1",
    location: "Neutral space",
    movement: "Right",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/right.gif",
    videoRef: "/refs/asl/vocab/right.mp4",
    altText: "ASL RIGHT: finger moves right",
    wlaslClipId: "right_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "up",
    gloss: "UP",
    category: "Directions",
    aslLexRank: 121,
    description: "1-handshape moves upward.",
    handshape: "1",
    location: "Neutral space",
    movement: "Upward",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/up.gif",
    videoRef: "/refs/asl/vocab/up.mp4",
    altText: "ASL UP: finger moves up",
    wlaslClipId: "up_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "down",
    gloss: "DOWN",
    category: "Directions",
    aslLexRank: 123,
    description: "1-handshape moves downward.",
    handshape: "1",
    location: "Neutral space",
    movement: "Downward",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/down.gif",
    videoRef: "/refs/asl/vocab/down.mp4",
    altText: "ASL DOWN: finger moves down",
    wlaslClipId: "down_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "near",
    gloss: "NEAR",
    category: "Directions",
    aslLexRank: 124,
    description: "Both hands close together.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Close together",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/near.gif",
    videoRef: "/refs/asl/vocab/near.mp4",
    altText: "ASL NEAR: hands close together",
    wlaslClipId: "near_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "far",
    gloss: "FAR",
    category: "Directions",
    aslLexRank: 125,
    description: "1-handshape moves far outward.",
    handshape: "1",
    location: "Neutral space",
    movement: "Far outward",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/far.gif",
    videoRef: "/refs/asl/vocab/far.mp4",
    altText: "ASL FAR: finger moves far",
    wlaslClipId: "far_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "in",
    gloss: "IN",
    category: "Directions",
    aslLexRank: 126,
    description: "1-handshape moves into palm.",
    handshape: "1",
    location: "Palm",
    movement: "Into palm",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/in.gif",
    videoRef: "/refs/asl/vocab/in.mp4",
    altText: "ASL IN: finger moves into palm",
    wlaslClipId: "in_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "out",
    gloss: "OUT",
    category: "Directions",
    aslLexRank: 127,
    description: "1-handshape moves out of palm.",
    handshape: "1",
    location: "Palm → outward",
    movement: "Out of palm",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/out.gif",
    videoRef: "/refs/asl/vocab/out.mp4",
    altText: "ASL OUT: finger moves out",
    wlaslClipId: "out_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "front",
    gloss: "FRONT",
    category: "Directions",
    aslLexRank: 128,
    description: "Flat hand moves forward.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Forward",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/front.gif",
    videoRef: "/refs/asl/vocab/front.mp4",
    altText: "ASL FRONT: hand moves forward",
    wlaslClipId: "front_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "back",
    gloss: "BACK",
    category: "Directions",
    aslLexRank: 129,
    description: "Thumb points over shoulder.",
    handshape: "Thumb",
    location: "Shoulder",
    movement: "Point back",
    orientation: "Thumb to back",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/back.gif",
    videoRef: "/refs/asl/vocab/back.mp4",
    altText: "ASL BACK: thumb points back",
    wlaslClipId: "back_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "next",
    gloss: "NEXT",
    category: "Directions",
    aslLexRank: 130,
    description: "Both hands move forward in sequence.",
    handshape: "Flat-B",
    location: "Neutral space",
    movement: "Forward sequence",
    orientation: "Palms down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/next.gif",
    videoRef: "/refs/asl/vocab/next.mp4",
    altText: "ASL NEXT: hands move forward",
    wlaslClipId: "next_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "between",
    gloss: "BETWEEN",
    category: "Directions",
    aslLexRank: 131,
    description: "1-handshape moves between two hands.",
    handshape: "1",
    location: "Between hands",
    movement: "Between",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/between.gif",
    videoRef: "/refs/asl/vocab/between.mp4",
    altText: "ASL BETWEEN: finger moves between",
    wlaslClipId: "between_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "around",
    gloss: "AROUND",
    category: "Directions",
    aslLexRank: 132,
    description: "1-handshape circles around.",
    handshape: "1",
    location: "Neutral space",
    movement: "Circle",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/around.gif",
    videoRef: "/refs/asl/vocab/around.mp4",
    altText: "ASL AROUND: finger circles",
    wlaslClipId: "around_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },

  // ── Adjectives & Descriptors (181-200) ─────────────────────────────────────
  {
    id: "good",
    gloss: "GOOD",
    category: "Adjectives",
    aslLexRank: 4,
    description: "Flat hand moves from chin to non-dominant palm.",
    handshape: "Flat-B",
    location: "Chin → palm",
    movement: "Downward",
    orientation: "Palm to chin",
    nmm: "Neutral or smile",
    animatedRef: "/refs/asl/vocab/good.gif",
    videoRef: "/refs/asl/vocab/good.mp4",
    altText: "ASL GOOD: hand moves from chin",
    wlaslClipId: "good_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "bad",
    gloss: "BAD",
    category: "Adjectives",
    aslLexRank: 7,
    description: "Flat hand moves from chin to non-dominant palm, flips.",
    handshape: "Flat-B",
    location: "Chin → palm",
    movement: "Downward + flip",
    orientation: "Palm to chin",
    nmm: "Negative expression",
    animatedRef: "/refs/asl/vocab/bad.gif",
    videoRef: "/refs/asl/vocab/bad.mp4",
    altText: "ASL BAD: hand flips from chin",
    wlaslClipId: "bad_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "big",
    gloss: "BIG",
    category: "Adjectives",
    aslLexRank: 17,
    description: "Both hands in 5-shape move apart.",
    handshape: "5",
    location: "Neutral space",
    movement: "Apart",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/big.gif",
    videoRef: "/refs/asl/vocab/big.mp4",
    altText: "ASL BIG: hands move apart",
    wlaslClipId: "big_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "small",
    gloss: "SMALL",
    category: "Adjectives",
    aslLexRank: 10,
    description: "Both hands in 5-shape move closer.",
    handshape: "5",
    location: "Neutral space",
    movement: "Closer",
    orientation: "Palms face each other",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/small.gif",
    videoRef: "/refs/asl/vocab/small.mp4",
    altText: "ASL SMALL: hands move closer",
    wlaslClipId: "small_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "hot",
    gloss: "HOT",
    category: "Adjectives",
    aslLexRank: 133,
    description: "Claw hand pulls away from mouth.",
    handshape: "Claw-5",
    location: "Mouth",
    movement: "Pull away",
    orientation: "Palm to mouth",
    nmm: "Hot expression",
    animatedRef: "/refs/asl/vocab/hot.gif",
    videoRef: "/refs/asl/vocab/hot.mp4",
    altText: "ASL HOT: hand pulls from mouth",
    wlaslClipId: "hot_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "cold",
    gloss: "COLD",
    category: "Adjectives",
    aslLexRank: 134,
    description: "Both hands shake in front of body.",
    handshape: "5",
    location: "Neutral space",
    movement: "Shake",
    orientation: "Palms in",
    nmm: "Cold expression",
    animatedRef: "/refs/asl/vocab/cold.gif",
    videoRef: "/refs/asl/vocab/cold.mp4",
    altText: "ASL COLD: hands shake",
    wlaslClipId: "cold_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "fast",
    gloss: "FAST",
    category: "Adjectives",
    aslLexRank: 135,
    description: "Dominant hand moves quickly across non-dominant.",
    handshape: "Flat-B",
    location: "Over palm",
    movement: "Fast across",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/fast.gif",
    videoRef: "/refs/asl/vocab/fast.mp4",
    altText: "ASL FAST: hand moves quickly",
    wlaslClipId: "fast_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "slow",
    gloss: "SLOW",
    category: "Adjectives",
    aslLexRank: 136,
    description: "Dominant hand moves slowly across non-dominant.",
    handshape: "Flat-B",
    location: "Over palm",
    movement: "Slow across",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/slow.gif",
    videoRef: "/refs/asl/vocab/slow.mp4",
    altText: "ASL SLOW: hand moves slowly",
    wlaslClipId: "slow_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "new",
    gloss: "NEW",
    category: "Adjectives",
    aslLexRank: 137,
    description: "Both hands in 5-shape move up from chest.",
    handshape: "5",
    location: "Chest → upward",
    movement: "Upward",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/new.gif",
    videoRef: "/refs/asl/vocab/new.mp4",
    altText: "ASL NEW: hands move up",
    wlaslClipId: "new_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "old",
    gloss: "OLD",
    category: "Adjectives",
    aslLexRank: 138,
    description: "Both hands in 5-shape move down from chin.",
    handshape: "5",
    location: "Chin → downward",
    movement: "Downward",
    orientation: "Palms to chin",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/old.gif",
    videoRef: "/refs/asl/vocab/old.mp4",
    altText: "ASL OLD: hands move down from chin",
    wlaslClipId: "old_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "beautiful",
    gloss: "BEAUTIFUL",
    category: "Adjectives",
    aslLexRank: 139,
    description: "Open hand circles face.",
    handshape: "5",
    location: "Face",
    movement: "Circle",
    orientation: "Palm to face",
    nmm: "Admiring expression",
    animatedRef: "/refs/asl/vocab/beautiful.gif",
    videoRef: "/refs/asl/vocab/beautiful.mp4",
    altText: "ASL BEAUTIFUL: hand circles face",
    wlaslClipId: "beautiful_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "ugly",
    gloss: "UGLY",
    category: "Adjectives",
    aslLexRank: 140,
    description: "1-handshape moves across nose with disgust.",
    handshape: "1",
    location: "Nose",
    movement: "Across",
    orientation: "Palm to nose",
    nmm: "Disgusted expression",
    animatedRef: "/refs/asl/vocab/ugly.gif",
    videoRef: "/refs/asl/vocab/ugly.mp4",
    altText: "ASL UGLY: finger moves across nose",
    wlaslClipId: "ugly_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "clean",
    gloss: "CLEAN",
    category: "Adjectives",
    aslLexRank: 141,
    description: "Dominant hand brushes across non-dominant palm.",
    handshape: "Flat-B",
    location: "Palm",
    movement: "Brush across",
    orientation: "Palm down",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/clean.gif",
    videoRef: "/refs/asl/vocab/clean.mp4",
    altText: "ASL CLEAN: hand brushes palm",
    wlaslClipId: "clean_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "dirty",
    gloss: "DIRTY",
    category: "Adjectives",
    aslLexRank: 142,
    description: "Both W-hands rub together.",
    handshape: "W",
    location: "Neutral space",
    movement: "Rub together",
    orientation: "Palms face each other",
    nmm: "Disgusted expression",
    animatedRef: "/refs/asl/vocab/dirty.gif",
    videoRef: "/refs/asl/vocab/dirty.mp4",
    altText: "ASL DIRTY: hands rub together",
    wlaslClipId: "dirty_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "easy",
    gloss: "EASY",
    category: "Adjectives",
    aslLexRank: 143,
    description: "Both hands in 5-shake move up轻松地.",
    handshape: "5",
    location: "Neutral space",
    movement: "Up + shake",
    orientation: "Palms in",
    nmm: "Relaxed expression",
    animatedRef: "/refs/asl/vocab/easy.gif",
    videoRef: "/refs/asl/vocab/easy.mp4",
    altText: "ASL EASY: hands move up lightly",
    wlaslClipId: "easy_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "hard",
    gloss: "HARD",
    category: "Adjectives",
    aslLexRank: 144,
    description: "Fist taps fist with effort.",
    handshape: "S",
    location: "Neutral space",
    movement: "Tap ×2",
    orientation: "Fist to fist",
    nmm: "Effort expression",
    animatedRef: "/refs/asl/vocab/hard.gif",
    videoRef: "/refs/asl/vocab/hard.mp4",
    altText: "ASL HARD: fists tap with effort",
    wlaslClipId: "hard_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "same",
    gloss: "SAME",
    category: "Adjectives",
    aslLexRank: 145,
    description: "Both Y-hands come together.",
    handshape: "Y",
    location: "Neutral space",
    movement: "Come together",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/same.gif",
    videoRef: "/refs/asl/vocab/same.mp4",
    altText: "ASL SAME: Y-hands come together",
    wlaslClipId: "same_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "different",
    gloss: "DIFFERENT",
    category: "Adjectives",
    aslLexRank: 146,
    description: "Both 1-hands separate from together.",
    handshape: "1",
    location: "Neutral space",
    movement: "Separate",
    orientation: "Palms in",
    nmm: "Neutral",
    animatedRef: "/refs/asl/vocab/different.gif",
    videoRef: "/refs/asl/vocab/different.mp4",
    altText: "ASL DIFFERENT: fingers separate",
    wlaslClipId: "different_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "right_correct",
    gloss: "RIGHT (correct)",
    category: "Adjectives",
    aslLexRank: 147,
    description: "Both hands in 5-shape move up affirmatively.",
    handshape: "5",
    location: "Neutral space",
    movement: "Upward",
    orientation: "Palms in",
    nmm: "Affirmative expression",
    animatedRef: "/refs/asl/vocab/right_correct.gif",
    videoRef: "/refs/asl/vocab/right_correct.mp4",
    altText: "ASL RIGHT (correct): hands move up",
    wlaslClipId: "right_correct_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
  {
    id: "wrong",
    gloss: "WRONG",
    category: "Adjectives",
    aslLexRank: 148,
    description: "Both 1-hands cross and separate.",
    handshape: "1",
    location: "Neutral space",
    movement: "Cross + separate",
    orientation: "Palms in",
    nmm: "Negative expression",
    animatedRef: "/refs/asl/vocab/wrong.gif",
    videoRef: "/refs/asl/vocab/wrong.mp4",
    altText: "ASL WRONG: fingers cross and separate",
    wlaslClipId: "wrong_0001",
    sourceAttr: "ASL University / Lifeprint.com",
  },
];

// Category list for filtering
export const CATEGORIES = [
  "Greetings",
  "Family",
  "Food",
  "Colors",
  "Numbers",
  "Emotions",
  "Time",
  "Verbs",
  "Places",
  "Directions",
  "Adjectives",
] as const;

// Helper: get signs by category
export function getSignsByCategory(category: string): SignEntry[] {
  return VOCABULARY_200.filter((s) => s.category === category);
}

// Helper: search signs by gloss
export function searchSigns(query: string): SignEntry[] {
  const q = query.toLowerCase();
  return VOCABULARY_200.filter(
    (s) =>
      s.gloss.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q)
  );
}

// Helper: get sign by ID
export function getSignById(id: string): SignEntry | undefined {
  return VOCABULARY_200.find((s) => s.id === id);
}

// Total count
export const TOTAL_SIGNS = VOCABULARY_200.length;
